filter:
    paths:
        - ./*

tools:
    sensiolabs_security_checker: true
    php_mess_detector:
        filter:
            excluded_paths:
              - spec/*
              - vendor/*
    php_analyzer:
        filter:
            excluded_paths:
              - spec/*
              - vendor/*
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - spec/*
                - vendor/*
    php_cpd:
        filter:
            excluded_paths:
              - spec/*
              - vendor/*
    php_loc:
        excluded_dirs:
            - spec/*
            - vendor/*
    php_pdepend:
        excluded_dirs:
            - spec/*
            - vendor/*
