language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"

# Allow to use container infrastructure
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini;
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer update --prefer-dist --no-interaction

script:
    - bin/phpspec run
    - bin/php-cs-fixer fix --dry-run -v --diff --config-file=.php_cs.php


notifications:
  slack: akeneo:fDZaQeRRj1gVtXCW3f2kQAxo
